# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c6fe0e6a60e346b63756f78367593eb8759c03013e671d277c00a665da15c02349f268f786b704cce332b3e39f5f50e29dadbc77a8752935c4ed1b2f11d7044

test:
  secret_key_base: 31fb145a271cc91a714cc1301c4993f2112c86ac42d9512f2f15b1ac103202115ba5124f2ded8284ba24ceac5804184c5fe1f5f73d4088dbf2dca17542930830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
